Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /cube/ HTTP/1.1" 200 1
"GET /cube/ HTTP/1.1" 200 1
"GET /cube/ HTTP/1.1" 200 1
"GET /heads_tails HTTP/1.1" 301 0
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2581
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
"GET /heads_tails/ HTTP/1.1" 200 5
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app2\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78319
Not Found: /index
"GET /index HTTP/1.1" 404 2425
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78319
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render('index.html')
           ^^^^^^^^^^^^^^^^^^^^
TypeError: render() missing 1 required positional argument: 'template_name'
"GET / HTTP/1.1" 500 63674
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render('index.html')
           ^^^^^^^^^^^^^^^^^^^^
TypeError: render() missing 1 required positional argument: 'template_name'
"GET / HTTP/1.1" 500 63811
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 10
"GET / HTTP/1.1" 200 10
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78453
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78453
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py", line 7, in index
    return render(request, 'my_app/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app/index.html
"GET / HTTP/1.1" 500 78590
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
"GET / HTTP/1.1" 200 338
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 421
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1610
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1493
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1492
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1511
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1688
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1505
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 955
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1014
"GET / HTTP/1.1" 200 1015
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 1015
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\my_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1844
Not Found: /images/image.png
Not Found: /styles/style.css
"GET /images/image.png HTTP/1.1" 404 2458
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1825
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
Not Found: /my_app/index.html
"GET /my_app/index.html HTTP/1.1" 404 2461
"GET / HTTP/1.1" 200 1818
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
Not Found: /my_app/about.html
"GET /my_app/about.html HTTP/1.1" 404 2461
Not Found: /index.html
"GET /index.html HTTP/1.1" 404 2440
"GET / HTTP/1.1" 200 1818
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1813
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1796
Not Found: /images/image.png
Not Found: /styles/style.css
"GET /images/image.png HTTP/1.1" 404 2458
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1796
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1796
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Not Found: /images/image.png
"GET /images/image.png HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1803
Not Found: /my_app/images/image.png
"GET /my_app/images/image.png HTTP/1.1" 404 2479
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1803
Not Found: /styles/style.css
Not Found: /my_app/images/image.png
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /my_app/images/image.png HTTP/1.1" 404 2479
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1887
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1887
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1842
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 1783
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1783
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET /about/ HTTP/1.1" 200 1015
"GET / HTTP/1.1" 200 1784
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
"GET / HTTP/1.1" 200 2004
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2458
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
Not Found: /hello
"GET /hello HTTP/1.1" 404 2533
Not Found: /magazin
"GET /magazin HTTP/1.1" 404 2539
"GET /magazin/hello HTTP/1.1" 301 0
"GET /magazin/hello/ HTTP/1.1" 200 26
"GET /magazin/hello2/ HTTP/1.1" 200 23
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
Not Found: /magazin
"GET /magazin HTTP/1.1" 404 2539
"GET /magazin/hello HTTP/1.1" 301 0
"GET /magazin/hello/ HTTP/1.1" 200 26
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
"GET /magazin HTTP/1.1" 301 0
"GET /magazin/ HTTP/1.1" 200 168
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2566
"GET /magazin/if HTTP/1.1" 301 0
"GET /magazin/if/ HTTP/1.1" 200 596
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 594
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
"GET /magazin/if/ HTTP/1.1" 200 594
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
"GET /magazin/if/ HTTP/1.1" 200 592
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
"GET /magazin/if/ HTTP/1.1" 200 595
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 667
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
"GET /magazin/if/ HTTP/1.1" 200 667
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /magazin/if/ HTTP/1.1" 200 643
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 29, in get_context_data
    context['total_price'] = int(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'DeferredAttribute'
"GET /magazin/if/ HTTP/1.1" 500 78460
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 29, in get_context_data
    context['total_price'] = int(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'DeferredAttribute'
"GET /magazin/if/ HTTP/1.1" 500 78460
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    context['total_price'] = decimal(Order.total_price)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decimal() argument 1 must be a unicode character, not DeferredAttribute
"GET /magazin/if/ HTTP/1.1" 500 78344
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\task_django\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Internal Server Error: /orders/2
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/2 HTTP/1.1" 500 132742
Internal Server Error: /orders/1
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/1 HTTP/1.1" 500 132732
Watching for file changes with StatReloader
Internal Server Error: /orders/1
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/1 HTTP/1.1" 500 132869
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Not Found: /orders
"GET /orders HTTP/1.1" 404 2677
Internal Server Error: /orders/10
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 31, in get_context_data
    orders = Order.objects.filter(user=user).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: customer, customer_id, id, ordered_at, products, total_price
"GET /orders/10 HTTP/1.1" 500 132731
Not Found: /order/10
"GET /order/10 HTTP/1.1" 404 2683
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
"GET /magazin/ HTTP/1.1" 200 168
Not Found: /magazin/1
"GET /magazin/1 HTTP/1.1" 404 3274
"GET /magazin/if HTTP/1.1" 301 0
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(pk=self.kwargs['id_user'])
                               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78185
Not Found: /magazin/if/1
"GET /magazin/if/1 HTTP/1.1" 404 3283
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(pk=self.kwargs['id_user'])
                               ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78185
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2242
Not Found: /styles/style.css
"GET /styles/style.css HTTP/1.1" 404 2707
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
Internal Server Error: /magazin/if/
Traceback (most recent call last):
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\venv\Lib\site-packages\django\views\generic\base.py", line 226, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py", line 30, in get_context_data
    user = User.objects.get(user=self.kwargs['id_user'])
                                 ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'id_user'
"GET /magazin/if/ HTTP/1.1" 500 78330
C:\Users\79282\PycharmProjects\Sasha\PYTHON\Framework_Django\Project_HW\task_django\magazin_app\views.py changed, reloading.
Watching for file changes with StatReloader
